version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ItemRaj@1562
      MYSQL_USER: nithin
      MYSQL_PASSWORD: ItemRaj@1562
      MYSQL_DATABASE: OSCGDB
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "nithin", "-pItemRaj@1562"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
